CREATE TABLE IF NOT EXISTS "Ventas" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"fecha" DATE NOT NULL,
	"monto" FLOAT NOT NULL,
	"cliente" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Articulos" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"nombre" VARCHAR(255) NOT NULL,
	"precio" FLOAT NOT NULL,
	"stock" INTEGER NOT NULL
);